import { PrismaService } from '../prisma/prisma.service';
import { CreateInvestmentHistoryDto } from './dto/create-investment-history.dto';
import { UpdateInvestmentHistoryDto } from './dto/update-investment-history.dto';
import { Decimal } from '@prisma/client/runtime/library';
export declare class InvestmentHistoryService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(userId: string, dto: CreateInvestmentHistoryDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: Decimal;
        costSingleStock: Decimal;
        quantity: Decimal;
        plannedPriceToSell: Decimal | null;
        saleDate: Date | null;
        salePrice: Decimal | null;
        income: Decimal | null;
        percentageIncome: Decimal | null;
    }>;
    findAllByUserId(userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: Decimal;
        costSingleStock: Decimal;
        quantity: Decimal;
        plannedPriceToSell: Decimal | null;
        saleDate: Date | null;
        salePrice: Decimal | null;
        income: Decimal | null;
        percentageIncome: Decimal | null;
    }[]>;
    findOne(id: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: Decimal;
        costSingleStock: Decimal;
        quantity: Decimal;
        plannedPriceToSell: Decimal | null;
        saleDate: Date | null;
        salePrice: Decimal | null;
        income: Decimal | null;
        percentageIncome: Decimal | null;
    } | null>;
    update(id: string, userId: string, dto: UpdateInvestmentHistoryDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: Decimal;
        costSingleStock: Decimal;
        quantity: Decimal;
        plannedPriceToSell: Decimal | null;
        saleDate: Date | null;
        salePrice: Decimal | null;
        income: Decimal | null;
        percentageIncome: Decimal | null;
    }>;
    delete(id: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: Decimal;
        costSingleStock: Decimal;
        quantity: Decimal;
        plannedPriceToSell: Decimal | null;
        saleDate: Date | null;
        salePrice: Decimal | null;
        income: Decimal | null;
        percentageIncome: Decimal | null;
    }>;
}
