import { InvestmentHistoryService } from './investment-history.service';
import { CreateInvestmentHistoryDto } from './dto/create-investment-history.dto';
import { UpdateInvestmentHistoryDto } from './dto/update-investment-history.dto';
export declare class InvestmentHistoryController {
    private readonly investmentHistoryService;
    constructor(investmentHistoryService: InvestmentHistoryService);
    create(userId: string, createInvestmentHistoryDto: CreateInvestmentHistoryDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: import("@prisma/client/runtime/library").Decimal;
        costSingleStock: import("@prisma/client/runtime/library").Decimal;
        quantity: import("@prisma/client/runtime/library").Decimal;
        plannedPriceToSell: import("@prisma/client/runtime/library").Decimal | null;
        saleDate: Date | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        income: import("@prisma/client/runtime/library").Decimal | null;
        percentageIncome: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    findAll(userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: import("@prisma/client/runtime/library").Decimal;
        costSingleStock: import("@prisma/client/runtime/library").Decimal;
        quantity: import("@prisma/client/runtime/library").Decimal;
        plannedPriceToSell: import("@prisma/client/runtime/library").Decimal | null;
        saleDate: Date | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        income: import("@prisma/client/runtime/library").Decimal | null;
        percentageIncome: import("@prisma/client/runtime/library").Decimal | null;
    }[]>;
    findOne(id: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: import("@prisma/client/runtime/library").Decimal;
        costSingleStock: import("@prisma/client/runtime/library").Decimal;
        quantity: import("@prisma/client/runtime/library").Decimal;
        plannedPriceToSell: import("@prisma/client/runtime/library").Decimal | null;
        saleDate: Date | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        income: import("@prisma/client/runtime/library").Decimal | null;
        percentageIncome: import("@prisma/client/runtime/library").Decimal | null;
    } | null>;
    update(id: string, userId: string, updateInvestmentHistoryDto: UpdateInvestmentHistoryDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: import("@prisma/client/runtime/library").Decimal;
        costSingleStock: import("@prisma/client/runtime/library").Decimal;
        quantity: import("@prisma/client/runtime/library").Decimal;
        plannedPriceToSell: import("@prisma/client/runtime/library").Decimal | null;
        saleDate: Date | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        income: import("@prisma/client/runtime/library").Decimal | null;
        percentageIncome: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    remove(id: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        userId: string;
        assetType: import(".prisma/client").$Enums.AssetType;
        boughtDate: Date;
        totalAmountInvested: import("@prisma/client/runtime/library").Decimal;
        costSingleStock: import("@prisma/client/runtime/library").Decimal;
        quantity: import("@prisma/client/runtime/library").Decimal;
        plannedPriceToSell: import("@prisma/client/runtime/library").Decimal | null;
        saleDate: Date | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        income: import("@prisma/client/runtime/library").Decimal | null;
        percentageIncome: import("@prisma/client/runtime/library").Decimal | null;
    }>;
}
